### PR TITLE
Remove R: Read bounds on structs

### PR DESCRIPTION
**Pull request by alisha17**
Remove R: Read bounds on structs as mentioned in Issue #88

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like CI may be failing though?

**Comment by alexcrichton** [comment]
Oh looks like this is also happening in https://github.com/alexcrichton/flate2-rs/pull/104

**Comment by alisha17** [comment]
Oops, i guess this PR should be closed then?

**Comment by alexcrichton** [comment]
Ok sure yeah, sorry for the delay! Ended up getting caught in travel...

If you've still got some extra time though I'd always appreciate help with issues like https://github.com/alexcrichton/flate2-rs/issues/75 or https://github.com/alexcrichton/flate2-rs/issues/76!

**Pull request closed without merging**
