### PR TITLE
Implemented multi member gz decoder

### PR DESCRIPTION
**Pull request by veldsla**
You mentioned in issue #41 that you were considering creating a separate type for the multistream gzip files. The nested loop method I used to parse these files in https://github.com/alexcrichton/flate2-rs/issues/41#issuecomment-219058833 becomes a bit convoluted when parsing multiple files.

Considering my rust beginner level I used it as an exercise. It works by calling finish_member instead of finish and checking if there are more bytes remaining in the buffer. If this is the case a new header read is attempted and the decoder is reset for the next member. Would this be what you had in mind?

### CODE REVIEW

**Comment by alexcrichton** [comment]
@veldsla I'm so sorry this sat here for so long! I had no idea this was here :(

In any case this looks excellent, thanks so much for implementing this! In the future feel free to ping me on any PR that sits for awhile!

**Comment by veldsla** [comment]
Haha, that's great. You did reference this PR in #44, so I just assumed you didn't want to add more functionality. Oh well assumptions are...😄

**Comment by alexcrichton** [comment]
Weird... I maybe accidentally archived the email?

**Comment by pmarks** [comment]
@alexcrichton - any chance we could get a crates.io release w/ this functionality?  Would like to start encouraging downstream packages to use MultiGzDecoder.  Many uses cases where MultiGz files are the norm (especially bioinformatics).

**Comment by veldsla** [comment]
There has been a library evaluation which among other things raised a point about the documentation (#87). I also noticed a doc has been swapped between a multi/normal reader. I will submit a PR for this. I'm guessing the next release will come when #89 is done?

**Comment by alexcrichton** [comment]
@pmarks certainly! I'll do a release right now

**Pull request merged**
