### PR TITLE
make mz_stream Send

### PR DESCRIPTION
**Pull request by kali**
Should answer #34.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Ok, I think this is good to go, thanks! 

Can you add the `unsafe impl` to the main crate on `stream::Stream`, however? I believe it should also be safe to declare that as `Sync` as well.

**Comment by kali** [comment]
I'm not sure about Sync really. There are a bunch a pointers and stuff in mz_stream that I would not want to see shared between two threads.

**Comment by kali** [comment]
Here you go. Stream is Send as well.

**Comment by alexcrichton** [comment]
`Sync` itself actually means that `&T` is safe to share among threads, which in this case it is because the type is correctly accessed via `&mut T` and such (e.g. there is no internal mutability). Can you also remove the `Sync` for `mz_stream` directly? (e.g. that doesn't belong in a `*-sys` crate)

**Comment by kali** [comment]
Understood, thanks for the clarifications :)

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
